### ISSUE TITLE
Problem with Terminal / Jekyll

### ISSUE THREAD

**Issue by nep2ne** [nep2ne/genevievelepine.design#1]
Hi @thomasjbradley,

I'm having an issue with Terminal. It was working earlier this morning, but now it's giving me the following error message:

Last login: Sun Oct  6 09:42:41 on ttys000
-bash: /Users/genevievelepine/.profile: No such file or directory
Genevieves-Design-Machine:~ genevievelepine$ bundle exec jekyll serve
bundler: failed to load command: jekyll (/usr/local/lib/ruby/gems/2.6.0/bin/jekyll)
Gem::Exception: can't find executable jekyll for gem jekyll. jekyll is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:462:in `block in replace_bin_path'
  /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:482:in `block in replace_bin_path'
  /usr/local/lib/ruby/gems/2.6.0/bin/jekyll:23:in `<top (required)>'
Genevieves-Design-Machine:~ genevievelepine$ bundle exec jekyll serve
bundler: failed to load command: jekyll (/usr/local/lib/ruby/gems/2.6.0/bin/jekyll)
Gem::Exception: can't find executable jekyll for gem jekyll. jekyll is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:462:in `block in replace_bin_path'
  /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:482:in `block in replace_bin_path'
  /usr/local/lib/ruby/gems/2.6.0/bin/jekyll:23:in `<top (required)>'
Genevieves-Design-Machine:~ genevievelepine$ 

Thanks,
G.

**Comment by nep2ne** [comment]
Hi again, @thomasjbradley, I figured out my problem. I had a basic section snippet inside my basic section html file, and it was breaking everything.

**Comment by thomasjbradley** [comment]
👍
