### ISSUE TITLE
Peer Review by Chris Libecap

### ISSUE THREAD

**Issue by libecap** [nep2ne/genevievelepine.design#2]
| | 0 points | 1 points | 2 points | 3 points |
**| 3 | 3 | 3 | 3 | 3 | SEE COMMENTS BELOW RUBRIC**
| **Creativeness** | Bland, boring | Fairly generic, but the colours are nice | Good, works very well and is unique enough | Wow! I never would have thought that would work so well! |
| **Effectiveness** | I don’t know what this is trying to do | The message isn’t completely clear and it’s difficult to use | It’s obvious and simple to use | The project is super effective and easy to use |
| **Quality** | Non-existent | Acceptable quality, more work could be done | Good quality, up to the expectations of the teacher | Stunning quality, this person rocks! |
| **Effort** | Zero effort, incomplete | Decent amount of effort | Goodly amount of effort that shows | Amazing, over-the-top amount of effort |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | Well indented, fully valid, good semantics |

HI G, This layout is awesome. It is clean, very nice structure, and I think really supports your portfolio pieces. I love the banner design as well. The only feedback I can think of is maybe considering using a higher contrast colour for your icon hover in your footer. If it doesn't go against your brand design, using a different colour might help  the hover state pop out a bit more.

**Comment by nep2ne** [comment]
Thanks Chris! I agree that the contrast in my hover icons in the footer could be more pronounced. Great feedback. Thanks again!
