### ISSUE TITLE
Peer Critique

### ISSUE THREAD

**Issue by Sebby-T** [nep2ne/genevievelepine.design#4]
Amazing work overall! It looks great and very responsive. I like the use of colours and layout of content. Especially the cards, great work on those. 

Few things of note:

- For the portfolio piece card. It may just be a one case issue, but I feel the white space below the image to be a little awkward. Good news though, it super easy to fix. Since it is in a grid, just add the class grid-middle. It will even the space on top and bottom making it feel nice.

- For the header navigations in general. If you're planning to make your—beautifully done—logo a link to your home page I think it should show up at smaller screen sizes. Easy way to implement is in a grid format make it sit on top of your navigation.

That's it!

| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Creativeness** | Bland, boring | Fairly generic, but the colours are nice | Good, works very well and is unique enough | **Wow! I never would have thought that would work so well!** |
| **Effectiveness** | I don’t know what this is trying to do | The message isn’t completely clear and it’s difficult to use | It’s obvious and simple to use | **The project is super effective and easy to use** |
| **Quality** | Non-existent | Acceptable quality, more work could be done | **Good quality, up to the expectations of the teacher** | Stunning quality, this person rocks! |
| **Effort** | Zero effort, incomplete | Decent amount of effort | Goodly amount of effort that shows | **Amazing, over-the-top amount of effort** |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | **Well indented, fully valid, good semantics** |

**Total**
14 points

The 2 points are only because I know you are not completely finished polishing the website (mine isn't either) at this point which is expected and totally fine.

**Comment by nep2ne** [comment]
Thanks Seb! Great suggestions re: the logo link and the portfolio card.
