### ISSUE TITLE
Pattern Library Critique - Laura Meguerditchian

### ISSUE THREAD

**Issue by moutonrebelle** [nep2ne/genevievelepine.design#5]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Creativeness** | Bland, boring | Fairly generic, but the colours are nice | Good, works very well and is unique enough | **Wow! I never would have thought that would work so well!** | 3pts
| **Effectiveness** | I don’t know what this is trying to do | The message isn’t completely clear and it’s difficult to use | It’s obvious and simple to use | **The project is super effective and easy to use** | 3pts
| **Quality** | Non-existent | Acceptable quality, more work could be done | Good quality, up to the expectations of the teacher | **Stunning quality, this person rocks!** | 3pts
| **Effort** | Zero effort, incomplete | Decent amount of effort | Goodly amount of effort that shows | **Amazing, over-the-top amount of effort** | 3pts
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | **Well indented, fully valid, good semantics** | 3pts

Total: 15/15 pts

Stunning website. I like your choice of colours. Your logo is unique and original. I really like your cards and font choice. Everything is responsive. Here's my feedback:

1. For your second card, it may be more user friendly if the images would take the whole width when the screen size is extra small.

Good job! :)

**Comment by nep2ne** [comment]
Thanks Laura! I like your suggestion about the second card images.
