### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Sebby-T** [nep2ne/genevievelepine.design#6]
Beautiful website design overall! I love the layout, font and colours. Good contrast and readability.

Issues:
- On the MK Tutoring Services project, the video on the bottom is set to private so I can't view it.

Could be intentional, but if not the fix is simple. It's just a setting on the video in youtube. Otherwise no other visible issues I can see. Great work!

Suggestions:
- On your homepage in the portfolio card section, the image to text ratio feels off at really large screen sizes.

If you wanted to change that you can add a wrapper to the section class that contains it all. and if you feel it squeezes it too much, you can create your own wrapper and change the max-width to w/e you prefer. I personally set it to 75em and that feels nicer.

Otherwise, amazing job! I love it.

**Comment by nep2ne** [comment]
Cool, I fixed my image-to-text ratio by changing the unit size for larger screens. Thanks for the suggestion! I also fixed the privacy settings on the video so that people could actually view them...
