### ISSUE TITLE
Design and Content Peer Review

### ISSUE THREAD

**Issue by libecap** [nep2ne/genevievelepine.design#7]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Pages & images** | Barely started | Missing lots of pages & images | Has most of the pages, some placeholder images | **All pages exist and are well done with complete imagery** |
| **Personality & design** | Bland, boring, just another graphic designer | Fairly generic, visual design could be pushed more | Quality layouts and unique, personable content & design | **Unique and recognizable as you, with engaging, personable content & design** |
| **Image quality** | Only placeholder images | Some portfolio piece images | Lots of images but low quality | **High quality portfolio images — and lots of them** |
| **Accessibility** | No considerations | Added some alt attributes, nothing else | Just the basics: alt attributes, roles | **Accessibility is well considered and tested** |
| **Text content** | Fake content only | Some real content, some fake | All real content but with lots of errors | **Real content, well written, no grammar or spelling errors** |
| **Responsiveness** | Not responsive | Works on some screens | Responsive but with lots of awkwardness | **Looks great on all screen sizes** |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | **Well indented, fully valid, good semantics** |

**21/21**

Hey G, I went through your website testing its responsiveness and on safari and chrome. And I didn't find any issues. You have a really strong website. It supports your portfolio pieces very well and your other works page is awesome for showing your versatility  and that you've done other amazing work outside of your main portfolio pieces. I even like how you included the sketches but as their own page per project. that was a really clever idea.

The only thing I could give as feedback would be the arrow you use for the user to return back to the top of the page. It can be hard to see sometimes on different backgrounds. One idea would be to have it be white but inside a small circle that uses the same fill you have currently.  kind of like a FAB  button you see on google's material design. 

Anyway, just a suggestion. I think it looks amazing as is. Great job!

**Comment by nep2ne** [comment]
Cool - I've been trying to figure out how to fix that up arrow, and this is a great solution. Imma give it a try. Thanks!
